### ISSUE TITLE
Connector obscured with grid-columns

### ISSUE THREAD

**Issue by meanderix** [terrastruct/TALA#88]
Here's a simple example:
```
grid-columns: 2
X -> Y: "HELLO WORLD"
```
Output:
![image](https://github.com/user-attachments/assets/8c021a6b-4e48-4087-84ed-fb3e7f935024)

**Comment by meanderix** [comment]
@alixander The main question is not about the gap size, but why the label obscures the connector.

**Comment by alixander** [comment]
It never looks good with the connector going through the label. When it's long enough, it'll show connector, with a gap for the label. Since it's not long enough, the gap is all you see. 

<img width="527" alt="Screenshot 2024-09-26 at 7 48 56 AM" src="https://github.com/user-attachments/assets/e335b7d2-3478-4df3-a302-ee222331ae07">
